version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cobranca-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cobranca_facil
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: ./api
    container_name: cobranca-api
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/cobranca_facil
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: http://localhost:3001
    container_name: cobranca-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mysql_data:
