version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cobranca-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cobranca_facil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: cobranca-api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cobranca_facil
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: http://localhost:3001
    container_name: cobranca-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
